### ISSUE TITLE
Installation via Homebrew?

### ISSUE THREAD

**Issue by denysdovhan** [Ors1mer/QuadcastRGB#16]
Hey, would it be possible to add an installation over homebrew?

Here is a formula cookbook: https://docs.brew.sh/Formula-Cookbook

Should be pretty easy to update the formula with this workflow: https://github.com/mislav/bump-homebrew-formula-action

**Comment by Ors1mer** [comment]
Hi there! Thank you for the links. I will look into this. The only issue is that I am missing a Mac to test the homebrew installation properly.

**Comment by tcorral** [comment]
Any news @Ors1mer about this issue? Has it been added to the roadmap?

**Comment by Ors1mer** [comment]
@tcorral Yes, I'm working on it. I will try to add `quadcastrgb` to `homebrew-core` eventually.

**Comment by Ors1mer** [comment]
The homebrew formula is now available at https://raw.githubusercontent.com/Ors1mer/QuadcastRGB/refs/heads/main/packages/homebrew/quadcastrgb.rb. I would like someone to test it.

Install with
```
HOMEBREW_NO_INSTALL_FROM_API=1 brew audit --new ./quadcastrgb.rb
HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source --verbose --debug ./quadcastrgb.rb
```
Also try running the test:
```
HOMEBREW_NO_INSTALL_FROM_API=1 brew test quadcastrgb
```
Besides `quadcastrgb` itself, also check if the manpage was installed:
```
man quadcastrgb
```
Be free to share the output of these commands, as well as any issues or warnings you noticed during the installation.

**Comment by tcorral** [comment]
I have tested it and I get an error on running the installatio commands, see screenshot.

`tomas@backbase. com@bb-system-3899 dnr-backbase-sdlc-prompt-library-26.05.2025 % HOMEBREW_NO_INSTALL_FROM_API=1 brew
audit -—new
•/ quadcastrgb.rb
HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source --verbose --debug
•/ quadcastrgb.rb
Error: Calling brew audit [path ...] is disabled! Use brew audit [name ...] instead.
Please report this issue:
https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading •/quadcastrgb. rb /opt/homebrew/Library/Homebrew/brew.rb (Formulary: :NullLoader): loading •/quadcastrgb.rb
/opt/homebrew/Library/Homebrew/brew.rb (Cask: :CaskLoader::NullLoader): loading •/quadcastrgb.rb /opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading •/quadcastrgb.rb
loading /quadcastrgb. rb
Warning: No available formula with the name "quadcastrgb".
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading quadcastrgb ==> Searching for similarly named formulae and casks...
Error: No formulae or casks found for quadcastrgb.
Error: Kernel. exit
/opt/homebrew/Library/Homebrew/extend/kernel.rb:115:in 'Kernel#exit' /opt/homebrew/Library/Homebrew/extend/kernel.rb:115:in 'Kernel#odie'
/ opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.5.12117/lib/types/private/methods/call_validation.
rb: 282:in 'UnboundMethod#bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.5.12117/lib/types/private/methods/call_validation.
rb: 282:in 'T::Private::Methods: :CallValidation validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.5.12117/lib/types/private/methods/_methods.rb:277:
in 'block in Kernel#_on_method_added'
/opt/homebrew/Library/Homebrew/cmd/install. rb:429:in 'Homebrew: :Cmd: :InstallCmd#run'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.5.12117/lib/types/private/methods/call_validation.
rb: 282:in 'UnboundMethod#bind_call'
/ opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.5.12117/lib/types/private/methods/call_validation.
rb: 282:in 'T::Private::Methods:: CallValidation validate_call'
opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.5.12117/1ib/types/private/methods/_methods.rb:277;
in 'block in Homebrew:: Cmd: : InstallCmd#_on_method_added' /opt/homebrew/Library/Homebrew/brew.rb:95:in '‹main›'`

**Comment by Ors1mer** [comment]
@tcorral Looks like homebrew did not attempt to install `quadcastrgb` from a local formula. Are you sure you downloaded and specified the correct path to `quadcastrgb.rb`?

If so, you may need to force homebrew to install the program from a local formula.

**Comment by Ors1mer** [comment]
@tcorral So I just tried running this on a freshly installed `brew` on Linux, and was able to get the `quadcastrgb` installed. There was an issue with tests, but I fixed that already.

Please, re-download [quadcastrgb.rb](https://raw.githubusercontent.com/Ors1mer/QuadcastRGB/refs/heads/main/packages/homebrew/quadcastrgb.rb).

I would suggest you to make sure that `homebrew` is up to date and `homebrew/core` is tapped:
```sh
brew update
brew tap homebrew/core
```

Then try these commands that I ran to install `quadcastrgb`:
```sh
# curl can be used instead
wget https://raw.githubusercontent.com/Ors1mer/QuadcastRGB/refs/heads/main/packages/homebrew/quadcastrgb.rb
# quadcastrgb should be installed after this command
HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source --verbose --debug ./quadcastrgb.rb
# this just runs tests specified in the formula
brew test quadcastrgb
```

If this still doesn't help, provide the output of all commands again as well as this one:
```sh
brew doctor
```

**Comment by tcorral** [comment]
It works.

**Comment by Ors1mer** [comment]
`quadcastrgb` is now available on `homebrew/core`. You may now install it with `brew install quadcastrgb` :)
